<script setup lang="ts">
import newTaskComponentVue from '@/components/task/newTaskComponent.vue';
import TaskListComponet from '@/components/task/taskListComponet.vue';

</script>

<template>
    <div class="container m-12 ">
        <div class="grid grid-cols-2 gap-12">
            <div class=" col m-5">
                <Suspense>
                    <newTaskComponentVue />
                    <template #fallback>
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                            style="margin: auto; background: rgb(99 102 241 / var(--tw-bg-opacity)); display: block; shape-rendering: auto;"
                            width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                            <path d="M10 50A40 40 0 0 0 90 50A40 42 0 0 1 10 50" fill="#e15b64" stroke="none">
                                <animateTransform attributeName="transform" type="rotate" dur="1s" repeatCount="indefinite"
                                    keyTimes="0;1" values="0 50 51;360 50 51">
                                </animateTransform>
                            </path>
                            <!-- [ldio] generated by https://loading.io/ -->
                        </svg>
                    </template>
                </Suspense>
            </div>
            <div class="col ">
                <TaskListComponet></TaskListComponet>
            </div>
        </div>
    </div>
</template>
